### ISSUE TITLE
Add profile icons for user and bot in chat screen

### ISSUE THREAD

**Issue by areebahmeddd** [1MindLabs/mivro-mobile-app#6]
Add small icons for both user and bot while chatting.

Ensure the user profile pic comes from the signed in values and bot has a constant pic (the pic for bot is saved in assets as bot.png)

**Comment by Amitkumarkoli** [comment]
hey! can I work on this issue??
 I am beginner in flutter.

**Comment by SpaceTesla** [comment]
> hey! can I work on this issue?? I am beginner in flutter.

@Amitkumarkoli this issue has already been closed. But you can work on other issues if you'd like to.
